name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write  # ✅ allows creating tags and releases

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # important for tags

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'  # or your Go version

      - name: Run Semantic Release
        uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}