name: Test Go the head branch of the pull-request
run-name: New or updated pull-request => Testing, building and scanning ${{ github.head_ref || github.ref_name }} branch

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      

      - name: Setup Go 1.25.1
        uses: actions/setup-go@v5
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.25.1'
          cache-dependency-path: go.sum

      - name: Build
        run: go build main.go
      - name: Test with the Go CLI
        run: go test ./lib -v